ARDUINO_HEADER=arduino-mk.h		# include our own header, which includes Arduino.h, and function prototypes

# tepmachcha, serial
F_CPU=8000000L
BOARD_TAG    = uno
AVRDUDE_ARD_BAUDRATE = 57600
ARDUINO_PORT = /dev/tty.SLAB_USBtoUART
ARDUINO_DIR   = /Applications/Arduino2.app/Contents/Java
#ARDUINO_TOOLS_DIR = /Applications/Arduino2.app/Contents/Java/hardware/tools

ARDUINO_LIBS = DS1337 Sleep_n0m1 Adafruit_FONA_Library SoftwareSerial Wire Fat16
include ~/src/Arduino/arduino-mk/Arduino.mk

